---
version: 0.5

# general information section - can contain summary information like if the service offers a managed service or has an open source offer.
# the details are then added with more extend in below blocks

name: The sample analyics service
website: https://sampleanalyticsservice.com
managed_service: yes
open_source_available: no




links:
  - name: 'Docs'
    url: https://sampleanalyticsservice.com/docs
  
  - name: 'Pricing'
    url: https://sampleanalyticsservice.com/pricing
  
  - name: 'Signup'
    url: https://sampleanalyticsservice.com/signup
  
  - name: 'Blog'
    url: https://sampleanalyticsservice.com/blog
  
  - name: 'Youtube'
    url: https://youtube.com/sampleanalyticsservice
  
  - name: 'Linkedin'
    url: https://linkedin.com/sampleanalyticsservice
  
managed_service:
  - model: managed
    pricing_plans:
      - plan: free 
        price: 0
        currency: USD


privacy:
  - cookieless_tracking: 
    - cookieless_tracking: yes
    - cookieless_implementation: anonymized ip & daily salt
    - doc_link: https://sampleanalyticsservice.com/docs/cookieless
  - server_locations:
    - location:
      - country: DE
      - vendor: AWS
